global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'student-monitoring'

scrape_configs:
  # Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  # MySQL
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql_exporter:9104']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'my_mysql_db'
  # Системные метрики
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'my_laptop'
  
  - job_name: 'custom_api'
    static_configs:
      - targets: ['custom_exporter:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'external_apis'
